Slight rewrite and breaking change
fstamour/disjoint-sets pull request #3
Opened 2024-11-18 08:23 UTC by adlai

This separate Pull Request is for changes you might not want to accept. One commit is some slight rewrites of things that bugged me in the source code, although they are subjective; the other is a breaking change that renames `disjoint-sets-union` to `disjoint-sets-unify`. I think it is confusing to experienced CL programmers, familiar with `cl:union` behaving non-destructively, that a function whose name includes "union" would modify its argument. It might be preferable to name it like `cl:nunion`, the destructive variant; however I think these are sufficiently different that it is better to use separate nomenclature.

2024-11-18 08:24 UTC, adlai commented
Please note that this Pull Request also includes the commits of both #1 and #2

2025-01-25 20:19 UTC, fstamour requested changes

2025-01-25 20:19 UTC, fstamour commented on disjoint-sets.lisp
> +(defun make-disjoint-sets (&optional (arity 0))
That's good

2025-01-25 20:19 UTC, fstamour commented on disjoint-sets.lisp
> +                          :adjustable t :fill-pointer t)))
That looks good

2025-01-25 20:19 UTC, fstamour commented on disjoint-sets.lisp
> -  (let ((new-id  (length sets)))
The previous version is more easily explainable (arguably).

I would prefer to keep it like it was even if the `let` is only there to give a name to an intermediate value.

2025-01-25 20:19 UTC, fstamour commented on disjoint-sets.lisp
> +    (if (= id parent) id             ; If `id' is the root, return it.
I put two `;` when the comment applies to the line below and only one `;` when it applies to the same line.

So put back that semicolon where you fund it

2025-01-25 20:19 UTC, fstamour commented on disjoint-sets.lisp
> +(defun disjoint-sets-unify (sets id1 id2)
https://github.com/adlai/disjoint-sets/commit/11a622dd2b2b9f717ceae6e3cd46d02848c4bdbd#commitcomment-150312237

"Unifify" is worse in my opinion, because it sounds theres some [unification](https://en.m.wikipedia.org/wiki/Unification_(computer_science)), which could be very confusing because this data structure can be used during unification ton detect cycles (a.k.a. "occurs check").

I might prefer "merge", which is a very common name for that operation.

BTW, I've put the `disjoint-set-` prefix because of the names `union` and `find` conflicted with CL's. I would be fine with removing the prefixes if the names don't clash anymore.

`nunion` might be good...

`disjoint-set-find` could be `find-representative`

2025-01-25 20:19 UTC, fstamour commented on disjoint-sets.lisp
> +=> 4 ; `sets' is modified.
Is the backtick/quote convention from emacs?

2025-01-25 20:32 UTC, adlai commented on disjoint-sets.lisp
> +(defun disjoint-sets-unify (sets id1 id2)
CL enables defining packages that obsolete ANSI X3J13, however the work needed to reach this stage is more than simply leaving out `:cl` from the `(:use ,what)` list; I believe you're already familiar with the efforts named CL21, and it might be possible to take it as inspiration for a rather monolithic file that only offers a few of the disjoint subsets of `(find-package :COMMON-LISP)` that are commonly used.

I think a different possible starting point for building this data independently of CL21 is surveying which parts of CL are used by popular libraries, and subtracting from this the functions that conflict too closely with the commonly-defined utilities; alternatively, someone on good terms with the HyperSpec's graph structure could probably barf it out with a few lines identifying the major clusters.

2025-01-25 20:36 UTC, adlai commented on disjoint-sets.lisp
> +=> 4 ; `sets' is modified.
Yes, it idiomatically causes the substring between the ticks to appear highlighted differently than by `font-lock-comment-face`, using `font-lock-constant-face`. I've not surveyed enough different themes and their failure modes to have a strong opinion about whether it is worth preserving, although because it works well and is quite similar to matched delimiters, I acquired the habit of marking constants thus.

2025-01-25 20:38 UTC, fstamour commented on disjoint-sets.lisp
> +(defun disjoint-sets-unify (sets id1 id2)
What do you think of "join" or "njoin"?

2025-01-25 20:46 UTC, fstamour commented on disjoint-sets.lisp
> +=> 4 ; `sets' is modified.
Ok, I checked the [docs](https://www.gnu.org/software/emacs/manual/html_node/elisp/Documentation-Tips.html), this looks good.

2025-01-25 20:51 UTC, adlai commented on disjoint-sets.lisp
> -  (let ((new-id  (length sets)))
ok; it's probably also more idiomatic if you think about this code being a reduction of more complicated code that operates on objects that store lots of graph metadata, rather than only the equivalence indices.

2025-01-25 20:58 UTC, fstamour commented on disjoint-sets.lisp
> -  (let ((new-id  (length sets)))
TL;DR: good point

---

another way of implementing this data structure is to use a hash-table with ids as keys and the set reprensentatives' id as value.

with that variant, ids can ben anything

I plan on implenting that in breeze, because I need it in the e-graph's implementation (IIUC what I have left to do there).

2025-01-25 22:40 UTC, adlai commented on disjoint-sets.lisp
> +(defun disjoint-sets-unify (sets id1 id2)
> What do you think of "join" or "njoin"?

I understand the intuition of that name; it's also similar to how that word is interpreted in the context of threading.

2025-01-26 01:29 UTC, fstamour approved these changes

2025-01-26 01:29 UTC, merged